# Archive gems (machine list)

**Date**: {{generated_date}}  
**Method**: {{method}}  
**Candidates**: {{n_candidates|int}} · **Rows**: {{n_gems|int}}  
**Curated reading**: `ARCHIVE_GEMS.md` (human pass over this pack)

These rows are cited excerpts the frames pointed at. Bots and `utACK`-only lines are dropped. Read the curated file first.

| Era | Frame | PR | Quote |
|-----|-------|---:|-------|
{% for item in gems %}
| {{item.era}} | {{item.frame}} | {{item.pr}} | {{item.quote_short}} |
{% endfor %}

**Generated by**: `scripts/reporting/generate_from_templates.py`
