# BIP Process Analysis Report

**Analysis Date**: {{generated_date}}  
**Data Sources**: BIP repository (GitHub), Bitcoin Core repository  
**Purpose**: Analyze governance patterns in the Bitcoin Improvement Proposal (BIP) process and compare to Core repository governance

---

## Overview

This report analyzes the governance patterns within the Bitcoin Improvement Proposal (BIP) repository: who proposes, who champions, how often BIPs show up in Core PRs, and how BIP-repo merge power compares to Core.

---

## Dump catalog

Not live GitHub. Counts are dump strings from `data/bips/bips.jsonl`, `bips_prs.jsonl`, and `bips_issues.jsonl`. As-of {{dump_catalog.as_of}} (wiki dump file mtime). Closed is a Status value. Merged is the dump bool.

**Wiki records**: {{dump_catalog.wiki|int}}

**Status**:
{% for item in dump_catalog.status %}
- {{item.name}}: {{item.count|int}}
{% endfor %}

**Type**:
{% for item in dump_catalog.type %}
- {{item.name}}: {{item.count|int}}
{% endfor %}

**Layer**:
{% for item in dump_catalog.layer %}
- {{item.name}}: {{item.count|int}}
{% endfor %}

**bitcoin/bips pull requests (dump)**:
- total: {{dump_catalog.prs.n|int}}
- open: {{dump_catalog.prs.open|int}}
- closed: {{dump_catalog.prs.closed|int}}
- merged: {{dump_catalog.prs.merged|int}} (merged true; closed is not merged)

**bitcoin/bips issues (dump)**:
- total: {{dump_catalog.issues.n|int}}
- open: {{dump_catalog.issues.open|int}}
- closed: {{dump_catalog.issues.closed|int}}

---

## Key Findings

### 1. Proposer Concentration

**Total BIPs**: {{proposer_analysis.total_bips|int}}  
**Total Proposers**: {{proposer_analysis.total_proposers|int}}  
**Proposal Concentration**:
- Top 3 proposers: {{proposer_analysis.concentration.top3_share|pct}} of all BIPs
- Top 5 proposers: {{proposer_analysis.concentration.top5_share|pct}} of all BIPs
- Top 10 proposers: {{proposer_analysis.concentration.top10_share|pct}} of all BIPs
- Gini Coefficient: {{proposer_analysis.concentration.gini_coefficient|round3}}

**Top Proposers**:
{% for item in proposer_analysis.top_proposers %}
- {{item.name}}: {{item.count|int}} BIP(s)
{% endfor %}

### 2. Champion Activity

**Total Champions**: {{champion_analysis.total_champions|int}} unique participants in BIP PRs

**Top Champions** (by PR activity):
{% for item in champion_analysis.top_champions %}
{{item.rank}}. {{item.name}}: {{item.count|int}} activities
{% endfor %}

### 3. Implementation Pipeline

- **BIPs with at least one Core PR mention**: {{implementation_analysis.bips_with_implementations|int}} / {{implementation_analysis.total_bips|int}} ({{implementation_analysis.implementation_rate|pct}})
- Mentions are a lower bound — not every implementation cites a BIP number.

### 4. Repository Comparison

**Actor Overlap**:
- BIP authors: {{repo_comparison.actor_overlap.bip_authors|int}}
- Core authors: {{repo_comparison.actor_overlap.core_authors|int}}
- Overlapping authors: {{repo_comparison.actor_overlap.overlapping_authors|int}}
- Overlap rate (of BIP authors): {{repo_comparison.actor_overlap.overlap_rate|pct}}

**BIP Merge Concentration**:
- Total merged PRs: {{repo_comparison.bip_merge_concentration.total_merged|int}}
- Unique mergers: {{repo_comparison.bip_merge_concentration.unique_mergers|int}}
- Top mergers:
{% for key, value in repo_comparison.bip_merge_concentration.top_mergers.items %}
  - {{key}}: {{value|int}} merges
{% endfor %}

---

## Methodology

- **Dump catalog**: preamble `Status` / `Type` / `Layer` and bitcoin/bips PR/issue `state` / `merged` as printed in the dump. Not live GitHub. Closed is not merged.
- **Proposer Extraction**: `Authors:` / `Author:` field in the BIP preamble (`<pre>` header)
- **Champion Identification**: Activity frequency (PRs authored, comments)
- **Implementation Tracking**: BIP number mentions in Core PR titles/bodies
- **Repo Comparison**: Actor overlap and merge concentration

**Limitations**:
- Preamble parsing can miss nonstandard headers
- Champion analysis is limited by available comment data
- Implementation tracking based on BIP mentions (may miss some)

---

## Implications

1. **Proposal concentration** is real but far milder than Core merge concentration.
2. **Champion network** ({{champion_analysis.total_champions|int}} participants) is broader than the proposer set — review labor is more distributed than authorship.
3. **About half of BIPs** leave a detectable trace in Core PRs; the rest stay spec-only, stalled, or implemented without a BIP citation.

**Data Source**: `analysis/findings/data/bip_analysis.json`  
**Generated by**: `scripts/reporting/generate_from_templates.py`
