# Commons mechanisms and the shared comparison

**Date:** {{generated_date}}  
**Machine-readable:** `findings/data/commons_dynamics_analysis.json`  
**Problem:** Which repeatable patterns in reviewer attention show up under year, size, and tenure controls, and what can a cross-repository rank actually say?

{{pin}}

The resource is reviewer attention and merge authority. The code is not the resource. Health indicators are a different set from the design-principle indicators.

## Confirmed effects

A row is here when the id starts with E, q is below 0.05, the 2024–2026 sign matches, the effect size is not negligible, and a standardized coefficient is at least 0.2 in absolute value.

{% for item in effects %}
### {{item.id}}

Estimate {{item.estimate}} (interval {{item.ci}}). q={{item.q}}. Holdout {{item.holdout}}. n={{item.n}}.

{{item.note}}

{% endfor %}

## Shared-indicator rank

The rank uses entry-wait variation, scope language, recurring dispute topics, open backlog, 24-month retention, merge concentration, bus factor, and median time to decision. Review labor, monitoring, and exits are in the Bitcoin Core profile and are not in this rank. Repositories with fewer than 7 years are omitted here.

{% for item in ranks %}
- {{item.repo}}: shared health {{item.health}}, shared principles {{item.principles}}, {{item.years}} years. Full-profile health {{item.full_health}}, full-profile principles {{item.full_principles}}.
{% endfor %}

Bitcoin Core on the shared subset is last among ranked repositories. Its full profile is health {{bitcoin_full_health}} and principles {{bitcoin_full_principles}}. That is a partial comparison, not a judgment that a tools repository is better governed.

## Lagged principle scores

{{lag_text}}

## The six effects on other repositories

{{cross_repo_text}}

The principle series and the repository table are in `GAP_CLOSURE.md`.

## What this cannot prove

{% for item in cannot %}
- {{item.text}}
{% endfor %}

**Generated by:** `scripts/reporting/generate_from_templates.py`
