# Conflict Resolution Analysis

**Date**: {{generated_date}}  
**Sources**: `temporal_analysis.json` (conflict_resolution_temporal) and `voting_bloc_conflict.json`

---

## Executive Summary

{{conflict_total|int}} conflicts across {{conflict_prs|int}} PRs ({{conflict_rate|pct}}). Average resolution time (conflict PRs with dates): {{avg_resolution|round1}} days.

Voting-bloc cohesion on conflict PRs: {{conflict_cohesion|pct}} ({{conflict_strong|int}} strong blocs) vs non-conflict {{nonconflict_cohesion|pct}} ({{nonconflict_strong|int}}). Pair counts are small — treat bloc cohesion as **suggestive**, not a voting-machine.

---

## Conflict volume by year

| Year | PRs | Conflicts | Rate | Avg days |
|------|----:|----------:|-----:|---------:|
{% for item in conflict_years %}
| {{item.year}} | {{item.total_prs_in_year|int}} | {{item.total_conflicts|int}} | {{item.conflict_rate|pct}} | {{item.avg_resolution_time_days|round1}} |
{% endfor %}

### Detection (GitHub text)

1. **NACK** keywords in comments  
2. **CHANGES_REQUESTED** reviews  
3. **Heated discussion**: 3+ comments with oppose/disagree/concern language  

A PR can trip more than one detector.

**2026 average days are right-censored** (the year is not complete). Do not compare 2026 resolution time to earlier years.

---

## Voting blocs during conflicts

| Pair | Same-side | Together | Cohesion |
|------|----------:|---------:|---------:|
{% for item in top_blocs %}
| {{item.m1}} / {{item.m2}} | {{item.together|int}} | {{item.total|int}} | {{item.cohesion|pct}} |
{% endfor %}

Most high-cohesion pairs have n < 15. Do not cite as durable factions.

**Generated by**: `scripts/reporting/generate_from_templates.py`
