# Contributor cross-reference

**Date:** {{generated_date}}  
**Status:** Schema seed (no rows)  
**Machine-readable:** `findings/data/governance_episode_ledger.json`

{{pin}}

This is **not an identity store**. Resolve a person once via `canonicalize_actor` / `canonical_maintainers.json`. This ledger only stores `canonical_key`, `github_handle`, `episodes_involved`, `episode_roles`, and `corpus_cites`. `person_role()` is merge-capability (`merge_keys` / `roster_without_keys` / `cannot_merge`), not episode role.

Allowed `episode_roles`: technical-objector, process-objector, merger, reviewer, redirector.

Contributor rows: {{contributor_count}}

---

| canonical_key | github_handle | episodes_involved | episode_roles | corpus_cites |
|---------------|---------------|-------------------|---------------|--------------|
{% for item in contributors %}
| {{item.canonical_key}} | {{item.github_handle}} | {{item.episodes_involved}} | {{item.episode_roles}} | {{item.corpus_cites}} |
{% endfor %}

No contributor rows in this seed. Do not copy aliases, emails, or merge-key lists into this file.

**Generated by:** `scripts/reporting/generate_from_templates.py`
