# Contributor Retention Analysis

## Executive Summary

Bitcoin Core has experienced **{{retention.exit_rate_1yr|pct}} contributor exit** (1-year threshold) with **{{retention.active_1yr|int}} of {{summary.total_contributors|int}}** contributors remaining active.

## Key Findings

| Metric | Value |
|--------|-------|
| **Total Contributors** | {{summary.total_contributors|int}} |
| **Active Contributors (1yr)** | {{retention.active_1yr|int}} ({{retention.retention_rate_1yr|pct}}) |
| **Exit Rate (1 year)** | {{retention.exit_rate_1yr|pct}} |
| **Exit Rate (2 year)** | {{retention.exit_rate_2yr|pct}} |

## Breakdown by Type

### PR Authors vs Participants

| Type | Count | % of Total | Exit Rate (1yr) |
|------|-------|------------|-----------------|
| **PR Authors** | {{authors.total|int}} | {{author_share|pct}} | {{authors.exit_rate_1yr|pct}} |
| **Participants Only** | {{participants_only.total|int}} | {{participant_share|pct}} | {{participants_only.exit_rate_1yr|pct}} |

*Participants = commented, reviewed, or created issues but never authored a PR*

### One-Time Contributors

- **{{one_time.total|int}} contributors ({{one_time.percentage|pct}})** did exactly 1 activity and left
- Exit rate: {{one_time.exit_rate_1yr|pct}}

### High-Quality Authors

- **{{quality.high_quality_authors|int}} authors** with 50%+ PR merge rate
- Exit rate: **{{quality.high_quality_exit_rate_1yr|pct}}**

### Established Authors (5+ merged PRs)

- **{{established_authors.total|int}} authors** (non-maintainers: {{established_authors.non_maintainers|int}}, maintainers: {{established_authors.maintainers|int}})
- Exit rate: **{{established_authors.exit_rate_1yr|pct}}** (non-maintainers {{established_authors.non_maintainer_exit_rate|pct}}, maintainers {{established_authors.maintainer_exit_rate|pct}})

## Activity Summary

| Activity Type | Count |
|---------------|-------|
| PRs Authored | {{activities.prs_authored|int}} |
| PR Comments | {{activities.pr_comments|int}} |
| PR Reviews | {{activities.pr_reviews|int}} |
| Issues Created | {{activities.issues_created|int}} |
| Issue Comments | {{activities.issue_comments|int}} |
| **Total Activities** | **{{activities.total|int}}** |

## Key Insights

1. **Massive Churn**: {{retention.exit_rate_1yr|pct}} of all contributors have exited (1-year threshold)
2. **Most Never Author PRs**: {{participant_share|pct}} only participate through comments/reviews/issues
3. **One-Time Dominates**: {{one_time.percentage|pct}} contribute once and leave
4. **Quality Irrelevant**: High-quality authors exit at {{quality.high_quality_exit_rate_1yr|pct}}
5. **Participants Exit More**: {{participants_only.exit_rate_1yr|pct}} exit rate for non-PR-authors
6. **Tenure among the still-active**: {{tenure.avg_tenure_years_active|round1}} years average

## Methodology

- **Contributor**: Anyone with GitHub activity on `bitcoin/bitcoin` (PR author, commenter, reviewer, issue creator, issue commenter). Delving / Bitcointalk / list-only names are **not** in these totals — see `GOVERNANCE_FRAMES.md`.
- **Active**: Activity within 365 days of the last observed GitHub event in this dump (not calendar today)
- **Exited**: No activity in that same 365-day window
- **Author**: Authored at least 1 PR
- **Participant**: Never authored a PR
- **High-Quality**: 50%+ PR merge rate (authors only)
- **One-Time**: Exactly 1 total activity

### Data Coverage

- **First Activity**: {{first_activity}}
- **Last Activity**: {{last_activity}}
- **Analysis Date**: {{analysis_date}}

*Source: `analysis/findings/data/contributor_analysis.json`*  
*Generated by `scripts/reporting/generate_from_templates.py` on {{generated_date}}*
