# Coordination Costs Analysis

**Date**: {{generated_date}}  
**Purpose**: Communication volume, participants, and decision time per PR  
**Machine-readable**: `analysis/findings/data/complexity_correlation.json`

---

## Executive Summary

Bitcoin Core governance has measurable coordination overhead: average **{{overall_msgs|round1}} messages** per PR (reviews + comments), **{{overall.avg_participants|round1}} participants**, across **{{overall.total_prs|int}}** PRs with file-change data. Governance load scales **{{scale_high_vs_low|round1}}×** from low- to high-complexity PRs ({{low.msgs|round1}} → {{high.msgs|round1}} messages).

---

## Overall Statistics

- **PRs analyzed**: {{overall.total_prs|int}}
- **Average files touched**: {{overall.avg_files|round1}}
- **Average reviews**: {{overall.avg_reviews|round1}}
- **Average participants**: {{overall.avg_participants|round1}}
- **Files↔reviews correlation**: {{correlation_files_vs_reviews|round3}} (weak linear; the step-function by complexity band is the useful signal)

---

## Coordination Costs by Complexity

| Band | PRs | Avg reviews | Avg comments | Avg messages | Avg participants | Avg decision days |
|------|----:|------------:|-------------:|-------------:|-----------------:|------------------:|
| Low (≤5 files) | {{low.count|int}} | {{low.avg_review_count|round1}} | {{low.avg_comment_count|round1}} | {{low.msgs|round1}} | {{low.avg_participant_count|round1}} | {{low.avg_decision_time|round1}} |
| Medium (6–15 files) | {{medium.count|int}} | {{medium.avg_review_count|round1}} | {{medium.avg_comment_count|round1}} | {{medium.msgs|round1}} | {{medium.avg_participant_count|round1}} | {{medium.avg_decision_time|round1}} |
| High (>15 files) | {{high.count|int}} | {{high.avg_review_count|round1}} | {{high.avg_comment_count|round1}} | {{high.msgs|round1}} | {{high.avg_participant_count|round1}} | {{high.avg_decision_time|round1}} |

Relative to low complexity:

- Medium messages: {{scale_med_vs_low|round1}}×
- High messages: {{scale_high_vs_low|round1}}×
- Medium decision time: {{scale_med_time|round1}}×
- High decision time: {{scale_high_time|round1}}×

---

## Reading

Coordination cost is real and stepwise: once a change leaves the “few files” band, review + comment volume jumps more than linearly. Decision *time* plateaus from medium to high — the extra cost shows up as more people and more messages, not proportionally longer clocks.

This JSON is GitHub-only volume. Informal-channel mentions (IRC / ML / Delving / Bitcointalk) are counted in cross-platform review weighting, not in these averages.

**Generated by**: `scripts/reporting/generate_from_templates.py`
