# Cross-Repository Comparison Report

**Analysis Date**: {{generated_date}}  
**Data Sources**: Bitcoin Core repository, BIPs repository  
**Purpose**: Compare governance patterns between Core and BIPs repositories

---

## Overview

This report compares actor overlap, merge-power concentration, and process outcomes between Bitcoin Core and the BIPs repository.

---

## Key Findings

### 1. Actor Overlap

| | Core | BIPs |
|--|------|------|
| Authors | {{actor_overlap.core_authors|int}} | {{actor_overlap.bip_authors|int}} |
| Maintainers (matched) | {{actor_overlap.core_maintainers|int}} | {{actor_overlap.bip_maintainers|int}} |

- **Overlapping authors**: {{actor_overlap.overlapping_authors|int}} ({{actor_overlap.overlap_rate_core|pct}} of Core authors; {{actor_overlap.overlap_rate_bip|pct}} of BIP authors)
- **Maintainer overlap**: {{actor_overlap.maintainer_overlap|int}}

### 2. Merge Concentration

| Metric | Core | BIPs |
|--------|------|------|
| Merged PRs | {{governance_comparison.core_repo.total_merged|int}} | {{governance_comparison.bips_repo.total_merged|int}} |
| Unique mergers | {{governance_comparison.core_repo.unique_mergers|int}} | {{governance_comparison.bips_repo.unique_mergers|int}} |
| Top-3 merge share | {{governance_comparison.core_repo.top3_share|pct}} | {{governance_comparison.bips_repo.top3_share|pct}} |
| Gini (mergers) | {{governance_comparison.core_repo.gini_coefficient|round3}} | {{governance_comparison.bips_repo.gini_coefficient|round3}} |

Core is **{{governance_comparison.comparison.concentration_difference|pct}}** more top-3 concentrated than BIPs.

**Core top mergers**:
{% for key, value in governance_comparison.core_repo.top_mergers.items %}
- {{key}}: {{value|int}}
{% endfor %}

**BIPs top mergers**:
{% for key, value in governance_comparison.bips_repo.top_mergers.items %}
- {{key}}: {{value|int}}
{% endfor %}

### 3. Power Portability (top-10 actors)

Only {{power_portability.overlap_count|int}} of the BIP-repo top 10 also sit in the Core top 10 ({{power_portability.power_overlap_rate|pct}}).

{% for item in power_portability.overlapping_actors %}
- **{{item.actor}}**: {{item.bip_power|int}} BIP merges → {{item.core_power|int}} Core merges
{% endfor %}

BIP top 10: {{power_portability.bip_top10_joined}}  
Core top 10: {{power_portability.core_top10_joined}}

### 4. Process Outcomes

| | Core | BIPs |
|--|------|------|
| Total PRs | {{process_comparison.core_process.total_prs|int}} | {{process_comparison.bip_process.total_prs|int}} |
| Merged | {{process_comparison.core_process.merged|int}} | {{process_comparison.bip_process.merged|int}} |
| Closed unmerged | {{process_comparison.core_process.rejected|int}} | {{process_comparison.bip_process.rejected|int}} |
| Merge rate | {{process_comparison.core_process.merge_rate|pct}} | {{process_comparison.bip_process.merge_rate|pct}} |

---

## Implications

1. **BIPs is a wider door**: hundreds of unique mergers vs ~{{governance_comparison.core_repo.unique_mergers|int}} on Core.
2. **Power does not transfer cleanly**: high BIP-repo activity is a weak predictor of Core merge authority ({{power_portability.power_overlap_rate|pct}} top-10 overlap).
3. **Merge rates are similar** (~{{process_comparison.core_process.merge_rate|pct}} vs ~{{process_comparison.bip_process.merge_rate|pct}}) even though concentration is not — BIPs distributes *who can merge*, Core concentrates it.

**Data Source**: `analysis/findings/data/cross_repo_comparison.json`  
**Generated by**: `scripts/reporting/generate_from_templates.py`
