# What the four open measurements show

**Date:** {{generated_date}}  
**Machine-readable:** `findings/data/gap_closure_analysis.json`  
**Problem:** Which of the measurements left open after the first four passes can be closed with the records already in the corpus?

{{pin}}

Related: `COMMONS_MECHANISMS.md` (the six effects and the shared-indicator rank), `FIRST_YEAR_TRAJECTORY.md` (the 340 patch-content leavers and the silence slope those indicators do not explain).

## Principle scores and later health

{{principle_lead}}

| Principle | Largest drop | Score that year | Year before | Year after | t+1 r | t+1 interval | t+1 q | t+2 r | t+2 q |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
{% for item in principle_rows %}
| {{item.label}} | {{item.decline}} | {{item.score}} | {{item.before}} | {{item.after}} | {{item.r1}} | {{item.ci1}} | {{item.q1}} | {{item.r2}} | {{item.q2}} |
{% endfor %}

{{holdout_lags}}

{% for item in principle_series %}
### {{item.label}}

{{item.table}}

{% endfor %}

P5 (sanctions) and P7 (organizing rights) have no scored year. Both are DATA UNAVAILABLE.

## Cross-repository effects

{{cross_lead}}

{% for item in repo_rows %}
- {{item.repo}}: shared health {{item.health}}, {{item.years}} years. {{item.effects}}
{% endfor %}

Repositories below seven years, omitted from the comparison:

{% for item in short_rows %}
- {{item.repo}}: {{item.reason}}. Shared health {{item.health}}.
{% endfor %}

Bitcoin Core reference, the pass-3 estimates. The q column here is the passes 1–5 family. `COMMONS_MECHANISMS.md` keeps the q from the pass-3 family. The estimates are the same numbers.

{% for item in reference_rows %}
- **{{item.id}}:** {{item.estimate}} (interval {{item.ci}}). Kind: {{item.kind}}. Passes 1–5 q={{item.q}}. 2024–2026 same sign: {{item.holdout}}. {{item.d_note}}
{% endfor %}

Spearman correlation of each effect size with repository health:

{% for item in spearman_rows %}
- {{item.id}}: {{item.text}}
{% endfor %}

{% for item in interpretations %}
{{item.text}}

{% endfor %}

## False-negative timeline

{{fn_lead}}

| Cohort | Leavers | False negatives | Rate |
| --- | --- | --- | --- |
{% for item in cohorts %}
| {{item.cohort}} | {{item.leavers}} | {{item.false_negatives}} | {{item.rate}} |
{% endfor %}

{{fn_holdout}}

## Silence and subsystem capacity

{{silence_lead}}

{{silence_slopes}}

{{silence_other}}

Entropy of the newcomer-pull-request distribution, in bits. The fitted slope uses these years.

| Year | Entropy |
| --- | --- |
{% for item in entropy_rows %}
| {{item.year}} | {{item.entropy}} |
{% endfor %}

{{entropy_shape}}

Newcomer pull requests by primary subsystem. A pull request that touches several subsystems is assigned to the one with the most files changed.

{{count_table}}

Silence rate and active reviewers at the two ends of the review-object window. An active reviewer has five or more review objects in that subsystem that year. Pre-2016 reviewer counts are DATA UNAVAILABLE.

| Subsystem | 2016 newcomers | 2016 silence | 2016 reviewers | 2023 newcomers | 2023 silence | 2023 reviewers |
| --- | --- | --- | --- | --- | --- | --- |
{% for item in endpoint_rows %}
| {{item.subsystem}} | {{item.n2016}} | {{item.s2016}} | {{item.r2016}} | {{item.n2023}} | {{item.s2023}} | {{item.r2023}} |
{% endfor %}

{{cell_reading}}

## What this closes

{% for item in closes %}
- {{item.text}}
{% endfor %}

## What this cannot prove

{% for item in cannot %}
- {{item.text}}
{% endfor %}

**Generated by:** `scripts/reporting/generate_from_templates.py`
