# Gini Coefficient: Explanation and Bitcoin Core Analysis

**Date**: {{generated_date}}  
**Machine-readable**: `analysis/findings/data/temporal_analysis.json` (`authorship_concentration_temporal`, `review_concentration_temporal`, `power_concentration_temporal`)

---

## What is the Gini Coefficient?

The **Gini coefficient** measures inequality from 0 to 1:

- **0.0** = Perfect equality
- **1.0** = Perfect inequality

Common reading: **< 0.3** low, **0.3–0.6** moderate, **≥ 0.6** high/extreme.

---

## Bitcoin Core Gini Coefficients

### Contribution inequality (PR authorship)

| Period | Gini | Top-10 author share | Unique authors | PRs |
|--------|-----:|--------------------:|---------------:|----:|
| Historical (2012–2020) | {{hist_author.gini_coefficient|round3}} | {{hist_author.top10_share|pct}} | {{hist_author.unique|int}} | {{hist_author.total|int}} |
| Recent (2021+) | {{recent_author.gini_coefficient|round3}} | {{recent_author.top10_share|pct}} | {{recent_author.unique|int}} | {{recent_author.total|int}} |

### Review concentration

| Period | Gini | Top-5 review share | Top-10 review share | Unique reviewers |
|--------|-----:|-------------------:|--------------------:|-----------------:|
| Historical (2012–2020) | {{hist_review.gini_coefficient|round3}} | {{hist_review.top5_share|pct}} | {{hist_review.top10_share|pct}} | {{hist_review.unique|int}} |
| Recent (2021+) | {{recent_review.gini_coefficient|round3}} | {{recent_review.top5_share|pct}} | {{recent_review.top10_share|pct}} | {{recent_review.unique|int}} |

### Merge authority (who clicks merge)

| Period | Gini | Top-3 merge share | Unique mergers |
|--------|-----:|------------------:|---------------:|
| Historical (2012–2020) | {{hist_merge.gini_coefficient|round3}} | {{hist_merge.top3_control|pct}} | {{hist_merge.unique_mergers|int}} |
| Recent (2021+) | {{recent_merge.gini_coefficient|round3}} | {{recent_merge.top3_control|pct}} | {{recent_merge.unique_mergers|int}} |

---

## Reading

Authorship and review stay **extreme**. Merge Gini is computed on the small merger set, so the more honest headline is **top-3 share** (still ~80%+). Inequality did not wash out after 2021; the names at the top changed (laanwj → fanquake) more than the shape of the distribution.

Gini here is GitHub-only. Informal channels redistribute *talk*, not merge keys. See `CROSS_PLATFORM_NETWORKS.md`.

**Generated by**: `scripts/reporting/generate_from_templates.py`
