# In-group review treatment

**Date:** {{generated_date}}  
**Machine-readable:** `findings/data/rsd_ingroup_analysis.json`  
**Problem:** Do pull requests from the current top reviewers get different treatment, and does that pattern match a population fingerprint of rejection sensitivity, negativity bias, or in-group preference?

{{pin}}

In-group is the top {{top_n}} by peer review-object volume strictly before the pull request. It is defined from {{defined_from}}. Headline window: {{headline_window}}. Pull requests used: {{n_prs}}.

## What holds

Decided in-group pull requests merge at {{merge_in}}. Decided out-group pull requests merge at {{merge_out}}. The difference is {{merge_gap}} (interval {{merge_ci}}).

No peer response: in-group {{silence_in}}, out-group {{silence_out}}, difference {{silence_gap}}.

Mean review tone: in-group {{tone_in}}, out-group {{tone_out}}, difference {{tone_gap}}.

Hours to first response: in-group {{hours_in}}, out-group {{hours_out}}, difference {{hours_gap}}.

Fingerprint scores: active social filtering {{score_filter}}, passive dropout {{score_dropout}}, structural access {{score_access}}. Closer reading: **{{resemblance}}**.

## What does not hold

A lead of 2 or more was required before naming a closer fingerprint. The scores do not produce one. Vocabulary differences are inside the negligible band. Nothing in this file is a diagnosis.

Conditions that failed or stayed unknown:

{% for item in unmet %}
- {{item.text}}
{% endfor %}

## What this cannot prove

{% for item in cannot %}
- {{item.text}}
{% endfor %}

**Generated by:** `scripts/reporting/generate_from_templates.py`
