# Interdisciplinary Analysis Report

**Date**: {{generated_date}}  
**Machine-readable**: `analysis/findings/data/interdisciplinary_analysis.json`

---

## Network centrality (merge / review)

**Top merge centrality**
{% for key, value in network_centrality.merge_centrality.items %}
- {{key}}: {{value|int}}
{% endfor %}

**Top review centrality**
{% for key, value in network_centrality.review_centrality.items %}
- {{key}}: {{value|int}}
{% endfor %}

Nodes in graph: {{network_centrality.total_nodes|int}}

---

## Information entropy

| Channel | Entropy | Normalized | Unique actors |
|---------|--------:|-----------:|--------------:|
| Merge | {{information_entropy.merge_entropy|round3}} | {{information_entropy.merge_normalized_entropy|round3}} | {{information_entropy.merge_unique_actors|int}} |
| Review | {{information_entropy.review_entropy|round3}} | {{information_entropy.review_normalized_entropy|round3}} | {{information_entropy.review_unique_actors|int}} |

Low normalized merge entropy = concentrated merge keys. Review entropy is higher — more people comment than merge.

---

## Game theory / coalitions

- Mutual cooperation pairs: {{game_theory_cooperation.mutual_cooperation_pairs|int}}
- One-way pairs: {{game_theory_cooperation.one_way_cooperation_pairs|int}}
- Cooperation rate: {{game_theory_cooperation.cooperation_rate|pct}}
- Coalition pairs: {{coalition_formation.coalition_pairs|int}}

**Top coalitions**
{% for item in coalition_formation.top_coalitions %}
- {{item.m1}} / {{item.m2}}: {{item.total|int}} directed merges (reciprocity {{item.reciprocity|pct}})
{% endfor %}

---

## Decision time by complexity

| Band | n | Avg days | CV |
|------|--:|---------:|---:|
| Low | {{organizational_decisions.low.count|int}} | {{organizational_decisions.low.avg_days|round1}} | {{organizational_decisions.low.coefficient_of_variation|round2}} |
| Medium | {{organizational_decisions.medium.count|int}} | {{organizational_decisions.medium.avg_days|round1}} | {{organizational_decisions.medium.coefficient_of_variation|round2}} |
| High | {{organizational_decisions.high.count|int}} | {{organizational_decisions.high.avg_days|round1}} | {{organizational_decisions.high.coefficient_of_variation|round2}} |

**Generated by**: `scripts/reporting/generate_from_templates.py`
