# Language Evolution

**Date**: {{generated_date}}  
**Sources**: GitHub PRs plus combined mailing lists, IRC, Delving, Bitcointalk  
**Machine-readable**: `analysis/findings/data/language_evolution.json`

Corpus: {{source_counts.prs|int}} PRs, {{source_counts.emails|int}} emails, {{source_counts.irc|int}} IRC, {{source_counts.delving|int}} Delving, {{source_counts.bitcointalk|int}} Bitcointalk.

---

## Terminology trends

| Term | First year (n) | Last year (n) | Total | Trend |
|------|----------------|---------------|------:|-------|
{% for item in terms %}
| {{item.term}} | {{item.first_year}} ({{item.first_count|int}}) | {{item.last_year}} ({{item.last_count|int}}) | {{item.total_mentions|int}} | {{item.trend}} |
{% endfor %}

First-year / last-year counts are the **first and last years with a nonzero mention**, not the edges of the corpus.

Common-English keywords (`lightning`, `script`, `taproot`, `witness`) can fire before the Bitcoin sense existed. Use the yearly series around known events (SegWit 2015–17, Taproot 2018–21), not first_year alone.

---

## Early adopters (first year on any channel)

{% for item in early %}
- **{{item.term}}** ({{item.first_year}}): {{item.users}}
{% endfor %}

**Generated by**: `scripts/reporting/generate_from_templates.py`
