# Maintainer Premium: Identity vs Merits (Fair Pass)

**Date:** {{generated_date}}  
**Status:** Fair/complete v{{version}} (author-prep + Phase 2 path/ACK/test-diff signals)  
**Machine-readable:** `findings/data/maintainer_premium.json`  
**Script:** `scripts/analysis/maintainer_premium.py`  
**Quality helpers:** `src/utils/pr_quality.py`  
**Rolled into:** `EXECUTIVE_SUMMARY.md` (Exclusive Privilege / Long-Term Problem)

## Question

Do outcomes favor **who** submitted a change — via merge privilege, reputation, or cold-start barriers — after fair controls, including **author-prep** matching (not false “quality”)?

## Fairness rules (applied)

| Rule | Treatment |
|------|-----------|
| Self-merge | Counted in **raw** rates; excluded from **peer-merge** success |
| Prior author merges | Reputation/access — report OR **with and without** this control |
| Closed-unmerged | Not equated to “Core rejected”; split into close proxies |
| Non-maintainer | Split cold-start / mid / established / top-volume |
| Identity label | Primary = ever-maintainer; sensitivity = active-at-creation |
| Author prep | `author_prep_score` = body length + test paths only (**no** reviews/LOC/merge) |
| Size substance | Descriptive only — **not** quality |
| Engagement | Reviews received — process only; not used for matching |
| Importance bands | **Excluded** (over-tags critical) — use **path_risk** instead |
| Concept/approach ACK | Received text flag — process/consensus signal, **not** author prep |
| CI | Unavailable on enriched corpus |

## Results that survive fairness cuts

### 1. Average-case raw gap is mostly self-merge privilege

| Window | Raw maint / non | Peer-merge maint / non | Self-merge share of maint merges |
|--------|----------------:|-----------------------:|---------------------------------:|
| All-time | {{all.raw_maint|pct}} / {{all.raw_non|pct}} | **{{all.peer_maint|pct}} / {{all.peer_non|pct}}** | {{all.self_merge_share_of_maintainer_merges|pct}} |
| 2022+ | {{y2022.raw_maint|pct}} / {{y2022.raw_non|pct}} | **{{y2022.peer_maint|pct}} / {{y2022.peer_non|pct}}** | {{y2022.self_merge_share_of_maintainer_merges|pct}} |

This share uses the premium timeline (`is_maintainer_at` on the enriched frame). The merge-pattern cite is **25.5% of 9,793** canonical-roster authored merges (`MERGE_PATTERN_BREAKDOWN.md`). Do not collapse the two.

### 2. Established outsiders are not broadly blocked

| Segment (non-maintainers) | All-time merge | 2022+ merge |
|---------------------------|---------------:|------------:|
| First PR (cold start) | **{{all.cold_start_merge|pct}}** | **{{y2022.cold_start_merge|pct}}** |
| Prior merges ≥5 | {{all.established_outsider_merge|pct}} | {{y2022.established_outsider_merge|pct}} |
| Top-20 volume authors | {{all.top20_outsider_merge|pct}} | {{y2022.top20_outsider_merge|pct}} |

Non-maintainer “merge rate” is **author-success**: a merge-key holder merged their PR. They cannot merge. 0% self-merge is structural, not inactivity.

### 3. Large outsider PRs almost never land

Closed ≥2k LOC: non-maint **{{all.large_2k_closed_non_merge|pct}}** all-time / **{{y2022.large_2k_closed_non_merge|pct}}** since 2022.

### 4. Author-prep matched gaps

Mean author-prep (maint / non): {{all.mean_prep_maint|round3}} / {{all.mean_prep_non|round3}}.  
High band (≥ 0.65): **{{all.high_author_prep_maint_merge|pct}} / {{all.high_author_prep_non_merge|pct}}** all-time (**{{all.high_author_prep_gap_pp|pp}}**); 2022+ **{{y2022.high_author_prep_gap_pp|pp}}**.

### 5. Phase 2 signals (descriptive)

| Signal | All-time gap | 2022+ gap |
|--------|-------------:|----------:|
| Concept/approach ACK received | {{all.phase2_concept_ack_gap_pp|pp}} | {{y2022.phase2_concept_ack_gap_pp|pp}} |
| High prep ∧ nontrivial test diff | {{all.phase2_high_prep_test_diff_gap_pp|pp}} | {{y2022.phase2_high_prep_test_diff_gap_pp|pp}} |
| CI | {{all.phase2_ci}} | {{y2022.phase2_ci}} |

### 6. Controlled logistic (sklearn)

Outcome is raw merge (includes self-merge). `is_maintainer` OR **with** prior-merges control: {{logistic_or_with_prior|round2}}. **Without** prior-merges control: {{logistic_or_without_prior|round2}}. Prior-merge count absorbs much of the identity coefficient.

### 7. Phase 3 sensitivity (`author_prep_sensitivity.json`)

| Variant | Gap (pp) | Non-maint merge | n_non |
|---------|---------:|----------------:|------:|
{% for item in prep_variants %}
| {{item.name}} | {{item.gap_pp|round1}} | {{item.non_merge_rate|pct}} | {{item.n_non_maintainer|int}} |
{% endfor %}

## Reading

{{interpretation}}

**n PRs**: {{n_prs|int}} (maintainer-authored {{n_maintainer_authored|int}})

**Generated by**: `scripts/reporting/generate_from_templates.py`
