# Merge Concentration and Deputy Patterns

**Date:** {{generated_date}}  
**Status:** Fair interpretation  
**Machine-readable:** `findings/data/high_volume_merger_deputies.json`  
**Related:** `scripts/analysis/merge_pattern_analysis.py`  
**Rolled into:** `EXECUTIVE_SUMMARY.md` (Power Concentration)

## Question

How thin is merge authority, and does the merger graph show recurring author funnels / co-reviewers?

## Results

### Modern window (2022+)

| Metric | Value |
|--------|------:|
| Merged PRs | {{recent_2022_plus.n_merged_prs|int}} |
| Top merger | `{{recent_2022_plus.top_merger}}` |
| Top-1 share | **{{recent_2022_plus.top_merger_share_pct|round1}}%** |
| Top-2 | **{{recent_top2_pct|round1}}%** |
| Top-3 | **{{recent_top3_pct|round1}}%** |

**2022+ top 5 mergers**:
{% for key, value in recent_2022_plus.top5_mergers.items %}
- {{key}}: {{value|int}}
{% endfor %}

Author funnels (≥40% of an author’s merges through `{{recent_2022_plus.top_merger}}`):

| Author | Funnels | Author total | Share |
|--------|--------:|-------------:|------:|
{% for item in recent_funnels %}
| {{item.author}} | {{item.count|int}} | {{item.author_total|int}} | {{item.pct|round1}}% |
{% endfor %}

**Top co-reviewers on `{{recent_2022_plus.top_merger}}` merges** (observational, not formal deputies):
{% for key, value in recent_coreviewers.items %}
- {{key}}: {{value|int}}
{% endfor %}

### All-time

`{{top_merger}}` {{top_merger_share_pct|round1}}% — historical; do not cite as the current picture.

## Fair reading

Modern merge authority is highly concentrated. Co-reviewer recurrence is **observational** (who appears on the same PRs), not proof of formal deputy rights. Still consistent with a small trusted filter.

For identity-vs-merits peer-review comparisons, see `MAINTAINER_PREMIUM_REPORT.md`.

## Reproduce

Artifact: `findings/data/high_volume_merger_deputies.json`

**Generated by**: `scripts/reporting/generate_from_templates.py`
