# Detailed Merge Pattern Breakdown

**Analysis Date**: {{generated_date}}  
**Data Source**: {{self_merge_breakdown.total_maintainer_merged|int}} maintainer-merged PRs with `merged_by`  
**Machine-readable**: `findings/data/merge_pattern_analysis.json`

**Note**: “Friend” and “janitor” are descriptive labels for observable merge graphs, not proof of informal office.

---

## 1. Self-Merge Rate Breakdown

- **Total maintainer merged PRs**: {{self_merge_breakdown.total_maintainer_merged|int}}
- **Self-merged**: {{self_merge_breakdown.total_self_merged|int}} ({{self_merge_breakdown.self_merge_rate|pct}})
- **Other-merged**: {{self_merge_breakdown.total_other_merged|int}}

| Review Count | Count | % of Self-Merges | % of All Maintainer PRs |
|-------------|------:|-----------------:|------------------------:|
| **Zero reviews** | {{zero.count|int}} | {{zero.rate|pct}} | {{zero.rate_of_all|pct}} |
| **One review** | {{one.count|int}} | {{one.rate|pct}} | {{one.rate_of_all|pct}} |
| **Two+ reviews** | {{two.count|int}} | {{two.rate|pct}} | {{two.rate_of_all|pct}} |

---

## 2. Friend patterns (≥20% of an author’s merges)

| Rank | Merger | Author | Merges | % of author’s PRs |
|-----:|--------|--------|-------:|------------------:|
{% for item in friends %}
| {{item.rank}} | {{item.merger}} | {{item.author}} | {{item.count|int}} | {{item.share|pct}} |
{% endfor %}

---

## 3. High-volume / janitor mergers

| Merger | Unique authors | Total merges | Avg per author |
|--------|---------------:|-------------:|---------------:|
{% for item in janitors %}
| {{item.merger}} | {{item.unique_authors|int}} | {{item.total_merges|int}} | {{item.avg_per_author|round1}} |
{% endfor %}

---

## 4. Individual maintainer self-merge

Average self-merge rate among analyzed maintainers: {{individual_avg|pct}}  
Average zero-review self-merge rate: {{individual_zero_avg|pct}}

| Maintainer | Total merged | Self-merge rate | Self / total |
|------------|-------------:|----------------:|--------------|
{% for item in maintainers %}
| {{item.maintainer}} | {{item.total_merged|int}} | {{item.self_merge_rate|pct}} | {{item.self_merged|int}} / {{item.total_merged|int}} |
{% endfor %}

See `MERGE_CONCENTRATION_DEPUTIES_REPORT.md` for the 2022+ fanquake window.

**Generated by**: `scripts/reporting/generate_from_templates.py`
