# Who the bar moved against

**Date:** {{generated_date}}  
**Machine-readable:** `findings/data/rsd_ingroup_analysis_v2.json`  
**Problem:** Did Bitcoin Core get harder for everyone, harder for newcomers, starved of review capacity, or does an in-group gap remain after calendar year is held fixed?

{{pin}}

Supported readings: {{supported}}.

## Period

Decided merge-rate slope: {{merge_slope}} per year (interval {{merge_slope_ci}}). The interval covers zero. Universal tightening is not supported.

Incumbent merge slope: {{incumbent_slope}} per year. Newcomer merge slope: {{newcomer_slope}} per year.

## Newcomers

Newcomer-by-year interaction on merge rate: {{merge_interaction}} per year (interval {{merge_interaction_ci}}). A negative number means the incumbent advantage widens. This reading is supported.

Newcomer-by-year interaction on getting no peer response: {{silence_interaction}} per year (interval {{silence_interaction_ci}}).

## Capacity

Pearson correlation of pull requests per active reviewer with newcomer silence: {{capacity_r}} (interval {{capacity_ci}}, {{capacity_years}} years). The interval is below zero. Capacity starvation is not supported. Silence rose while the queue per reviewer fell.

## Group gap after year controls

In-group log-odds without year fixed effects: {{logit_raw}} (odds ratio {{or_raw}}). With year fixed effects: {{logit_year}} (odds ratio {{or_year}}, interval {{logit_year_ci}}). The coefficient stays positive. Sample size {{logit_n}}.

The two-year-cohort pooled Cohen's d of {{cohort_d}} is the cumulative top 20, not the rolling set. Rolling ever-entered: {{rolling_n}}. About {{fraction_remaining}} of the raw first-year merge gap remains inside those two-year cohorts (cohort fixed-effect gap {{cohort_fe_gap}}).

## What this cannot prove

Year fixed effects are in the model because outcomes are time-structured. They are not evidence that the whole project tightened. The residual in-group coefficient is not a psychological finding.

**Generated by:** `scripts/reporting/generate_from_templates.py`
