# Novel Interpretations

**Date**: {{generated_date}}  
**Machine-readable**: `findings/data/novel_interpretations.json`

These are **descriptive clusters** from merge/review graphs, not psychological diagnoses.

---

## Behavioral clusters

**High self-merge + high merge authority**
{% for item in behavioral_clusters.clusters.high_self_merge_high_authority %}
- {{item.maintainer}}: self-merge {{item.self_merge_rate|pct}}, authority {{item.merge_authority|int}}
{% endfor %}

**High self-merge + lower authority**
{% for item in behavioral_clusters.clusters.high_self_merge_low_authority %}
- {{item.maintainer}}: self-merge {{item.self_merge_rate|pct}}, authority {{item.merge_authority|int}}
{% endfor %}

**Low self-merge + high authority**
{% for item in behavioral_clusters.clusters.low_self_merge_high_authority %}
- {{item.maintainer}}: self-merge {{item.self_merge_rate|pct}}, authority {{item.merge_authority|int}}
{% endfor %}

---

## Power hierarchy (maintainer-to-maintainer merges)

{% for item in power_hierarchy.hierarchy %}
- **{{item.merger}}**: {{item.total_maintainer_merges|int}} maintainer merges
{% endfor %}

---

## Review reciprocity (sample)

Reciprocity here is “A reviews B and B reviews A,” not formal vote-trading.

{% for item in reciprocity_top %}
- {{item.pair}}: {{item.count|int}}
{% endfor %}

---

## Reading

The same few names appear as high-authority self-mergers, hierarchy apex, and reciprocal reviewers. That is consistent with a small trusted filter, not with a wide peer jury. Pair it with `MAINTAINER_PREMIUM_REPORT.md` (identity vs prep) and `MERGE_CONCENTRATION_DEPUTIES_REPORT.md` (2022+ fanquake share).

**Generated by**: `scripts/reporting/generate_from_templates.py`
