# PR Importance vs Review Quality Analysis

**Date**: {{generated_date}}  
**Status**: Generated from `findings/data/pr_importance_matrix.json`

---

## Methodology

**Review Counting**: Quality-weighted (GitHub, ACK, IRC, combined mailing lists, Delving, Bitcointalk), MAX per reviewer  
**PR Classification**: Multi-criteria (file changes, file types, keywords, labels)

### Importance Levels

1. **TRIVIAL**: Typo fixes, formatting, trivial changes
2. **LOW**: Documentation, tests, housekeeping
3. **NORMAL**: Regular code changes
4. **HIGH**: Significant features, refactoring
5. **CRITICAL**: Consensus / security / protocol (or large + consensus-tagged)

---

## The Question

**"A lot of PRs that get merged are housekeeping type things that arguably don't need much if any review. Are we accounting for that?"**

Zero-review rates fall as importance rises, but they do **not** go to zero on critical work.

## Zero-Review Rates by PR Type

| PR Type | Total PRs | Zero Review | Zero-Review Rate | Maintainer zero-review | Avg Review Score |
|---------|-----------|-------------|------------------|------------------------|------------------|
{% for item in types %}
| **{{item.name}}** | {{item.total|int}} | {{item.zero_review|int}} | **{{item.zero_review_rate|pct}}** | {{item.maintainer_zero_review_rate|pct}} | {{item.avg_review_score|round2}} |
{% endfor %}

## Reading

Housekeeping (trivial/low) has the highest zero-review rates. Critical PRs are better reviewed and still show a **{{critical_zero|pct}}** zero-review rate — “it was just cleanup” does not explain the overall pattern.

**Generated by**: `scripts/reporting/generate_from_templates.py`
