# Rejection anatomy

**Date:** {{generated_date}}  
**Status:** Schema seed (empty objection cells)  
**Machine-readable:** `findings/data/governance_episode_ledger.json`

{{pin}}

This is **episode anatomy**, not GitHub matcher counts. Counts: `STALLED_PROPOSALS_REPORT.md`. Quotes: `ARCHIVE_GEMS.md`.

---

{% for item in episodes %}
## {{item.proposal}}

- **episode_id:** `{{item.episode_id}}`
- **parent:** {{item.parent_episode}}
- **venue:** {{item.venue}}
- **github_anchors:** {{item.github_anchors}}
- **existing_findings:** {{item.existing_findings}}
- **technical_objections:** {{item.technical_objections}}
- **process_objections:** {{item.process_objections}}
- **outcome:** {{item.outcome}}
- **corpus_cites:** {{item.corpus_cites}}

{% endfor %}

**Generated by:** `scripts/reporting/generate_from_templates.py`
