# Release Signing Authority Analysis Report

**Analysis Date**: {{generated_date}}  
**Data Sources**: Bitcoin Core release signatures  
**Purpose**: Analyze release signing authority concentration and patterns

---

## Overview

This report analyzes who signs Bitcoin Core releases, tracking signing authority concentration over time.

---

## Key Findings

### 1. Signing Authority Concentration

**Total Releases**: {{concentration.total_releases|int}}  
**Signed Releases**: {{concentration.signed_releases|int}} ({{concentration.signing_rate|pct}})  
**Unique Signers**: {{concentration.unique_signers|int}}

**Concentration Metrics**:
- Gini Coefficient: {{concentration.concentration_metrics.gini_coefficient|round3}}
- Top 5 Signers: {{concentration.concentration_metrics.top_5_share|pct}} of all signed releases
- Top 10 Signers: {{concentration.concentration_metrics.top_10_share|pct}} of all signed releases

**Top Signers**:
{% for item in concentration.top_signers %}
{{item.rank}}. {{item.name}}: {{item.count|int}} releases ({{item.share|pct}})
{% endfor %}

### 2. Temporal Patterns (recent years)

| Year | Releases | Signed | Signing rate | Unique signers |
|------|----------|--------|--------------|----------------|
{% for item in recent_years %}
| {{item.year}} | {{item.total|int}} | {{item.signed|int}} | {{item.signing_rate|pct}} | {{item.unique_signers|int}} |
{% endfor %}

### 3. Identification

- Identified signers on signed releases: {{transparency.identification_rate|pct}}
- Cryptographic verification of detached signatures in this corpus: {{transparency.verification_rate|pct}} (identity from filename/email, not GPG verify)
- Documented email and display-name variants of the same person are counted once (for example `laanwj@gmail.com`, `laanwj@protonmail.com`, and the GitHub noreply address are Wladimir J. van der Laan)

---

## Implications

1. **High concentration**: {{concentration.concentration_metrics.top_5_share|pct}} of signed releases come from the top 5 identities.
2. **Historical continuity**: Wladimir van der Laan remains the all-time volume leader; recent years show a smaller active signer set.
3. **Transition**: `fanquake` and `glozow` appear in the recent signer set — signing authority moved with merge authority, not independently of it.

**Data Source**: `analysis/findings/data/release_signing.json`  
**Generated by**: `scripts/reporting/generate_from_templates.py`
