# Enhanced PR Review Quality Analysis

**Analysis Date**: {{generated_date}}  
**Data Source**: {{total_prs|int}} PRs  
**Machine-readable**: `findings/data/review_quality_enhanced.json`

This is **GitHub review-body** quality (length, rubber-stamps, questions). Informal-channel mentions are listed below and are **not** mixed into these averages.

---

## Temporal Trends

| Year | Reviews | Avg Body Length | Rubber Stamp Rate | Question Rate |
|------|--------:|----------------:|------------------:|--------------:|
{% for item in years %}
| {{item.year}} | {{item.total_reviews|int}} | {{item.avg_body_length|round1}} | {{item.rubber_stamp_rate|pct}} | {{item.question_rate|pct}} |
{% endfor %}

- Body length {{first_year}} → {{last_year}}: {{first_len|round1}} → {{last_len|round1}} chars
- Rubber-stamp {{first_year}} → {{last_year}}: {{first_stamp|pct}} → {{last_stamp|pct}}

---

## Review type distribution

| Type | Count | Share |
|------|------:|------:|
| Approved | {{review_types.overall.approved|int}} | {{review_types.overall.approval_rate|pct}} |
| Changes requested | {{review_types.overall.changes_requested|int}} | {{review_types.overall.changes_requested_rate|pct}} |
| Commented | {{review_types.overall.commented|int}} | — |

---

## PR size vs review quality

| Size | PRs | Reviews / PR | Avg body length | Rubber-stamp rate |
|------|----:|-------------:|----------------:|------------------:|
{% for item in sizes %}
| {{item.name}} | {{item.prs|int}} | {{item.reviews_per_pr|round1}} | {{item.avg_body_length|round1}} | {{item.rubber_stamp_rate|pct}} |
{% endfor %}

---

## Top reviewers by volume

| Reviewer | Reviews | Avg body | Approval rate | Changes-requested |
|----------|--------:|---------:|--------------:|------------------:|
{% for item in top_reviewers %}
| {{item.name}}{{item.tag}} | {{item.total_reviews|int}} | {{item.avg_body_length|round1}} | {{item.approval_rate|pct}} | {{item.changes_requested_rate|pct}} |
{% endfor %}

---

## Informal-channel PR mentions

These are `#NNNN` / pull-URL references on IRC, mailing lists, Delving, and Bitcointalk. They are a separate corpus from GitHub review bodies.

| Channel | PRs with discussion | Messages |
|---------|--------------------:|---------:|
{% for item in cross_platform.channel_rows %}
| {{item.name}} | {{item.prs|int}} | {{item.messages|int}} |
{% endfor %}

- Unique PRs mentioned off-GitHub: {{cross_platform.unique_prs_mentioned|int}}

**Generated by**: `scripts/reporting/generate_from_templates.py`
