# Stalled Proposals: Case Dossiers (Fair Cite)

**Date:** {{generated_date}}  
**Status:** Fair cite v{{version}}  
**Machine-readable:** `findings/data/stalled_proposal_dossiers.json`  
**Script:** `scripts/analysis/stalled_proposal_dossiers.py`  
**Rolled into:** `EXECUTIVE_SUMMARY.md` (Long-Term Problem)

## Question

Which named “research-complete / delayed” proposals have **GitHub timelines strong enough to cite**, without counting scaffolding as delivery or noisy keywords as proof?

PR matcher **counts**. Qualitative episode anatomy and stated-agreement NACK status: `REJECTION_ANATOMY.md`, `STALLED_AGREEMENT_LEDGER.md`.

## Docket

| Proposal | PRs | Merged | Closed unmerged | Open | Longest unmerged (days) | Cite as |
|----------|----:|-------:|----------------:|-----:|------------------------:|---------|
{% for item in proposals %}
| **{{item.title}}** | {{item.n_prs|int}} | {{item.n_merged|int}} | {{item.n_closed_unmerged|int}} | {{item.n_open|int}} | {{item.max_days_to_decision|round1}} | {{item.claim}} |
{% endfor %}

## Erlay detail (corrected matcher)

{% for key, value in erlay_by_role.items %}
- **{{key}}**: n={{value.n|int}}, merged={{value.merged|int}}, closed_unmerged={{value.closed_unmerged|int}}, open={{value.open|int}}
{% endfor %}

{{erlay_full_protocol_outcome}}

## Method limits (fairness)

{% for item in fair_cite_guidance %}
- {{item}}
{% endfor %}
- Keyword dossiers ≠ exhaustive history; BIP / mailing-list / Delving paths are not the primary matcher.
- Closed-unmerged includes author withdrawal and staging PRs.

## Reproduce

```bash
venv/bin/python scripts/analysis/stalled_proposal_dossiers.py
venv/bin/python scripts/reporting/generate_from_templates.py
```

**Generated by**: `scripts/reporting/generate_from_templates.py`
