# Stalled agreement ledger

**Date:** {{generated_date}}  
**Status:** Schema seed (`nack_exists` unknown until cited)  
**Machine-readable:** `findings/data/governance_episode_ledger.json`

{{pin}}

This is a **candidate list** of named research-complete / delayed proposals. `nack_exists` is measured, not a membership test. It is not `STALLED_PROPOSALS_REPORT.md` (PR matcher counts) and must not be named `STALLED_PROPOSALS.md`.

full-RBF is not on this seed list. Archive gems already store NACKs for that episode.

---

| Proposal | episode_id | First proposed | Last activity | Stated reason | nack_exists | nack_source | corpus_cites | existing_findings |
|----------|------------|----------------|---------------|---------------|-------------|-------------|--------------|-------------------|
{% for item in agreement_stalls %}
| {{item.proposal}} | `{{item.episode_id}}` | {{item.first_proposed}} | {{item.last_activity}} | {{item.stated_reason_for_stall}} | {{item.nack_exists}} | {{item.nack_source}} | {{item.corpus_cites}} | {{item.existing_findings}} |
{% endfor %}

**Generated by:** `scripts/reporting/generate_from_templates.py`
