# Comprehensive Temporal Analysis Report

**Date**: {{generated_date}}  
**Purpose**: Self-merge, era, power, conflict, and concentration patterns over time  
**Machine-readable**: `analysis/findings/data/temporal_analysis.json`

---

## Executive Summary

Self-merge rates stay in a moderate band while **zero-review self-merges collapse** after 2016. Newer maintainer cohorts review more and self-merge less. Merge authority remains highly concentrated in every period.

---

## 1. Temporal Self-Merge Patterns

| Year | Total PRs | Self-Merge Rate | Zero-Review Self-Merge | Avg Reviews |
|------|-----------|-----------------|------------------------|-------------|
{% for item in self_merge_years %}
| {{item.year}} | {{item.total|int}} | {{item.self_merge_rate|pct}} | {{item.zero_review_self_merge_rate|pct}} | {{item.avg_reviews|round1}} |
{% endfor %}

- First-year vs latest-year zero-review self-merge: {{first_zero|pct}} → {{last_zero|pct}}
- Review depth: {{first_reviews|round1}} → {{last_reviews|round1}}

---

## 2. Maintainer Era Patterns

| Era | Members | PRs | Self-Merge | Zero-Review | Avg Reviews |
|-----|---------|----:|-----------:|------------:|------------:|
{% for item in eras %}
| **{{item.label}}** | {{item.n_members|int}} | {{item.total_prs|int}} | {{item.self_merge_rate|pct}} | {{item.zero_review_rate|pct}} | {{item.avg_reviews|round1}} |
{% endfor %}

---

## 3. Merge-authority concentration by period

| Period | Merges | Unique mergers | Top-3 share | Gini |
|--------|-------:|---------------:|------------:|-----:|
{% for item in power_periods %}
| {{item.period}} | {{item.total_merges|int}} | {{item.unique_mergers|int}} | {{item.top3_control|pct}} | {{item.gini_coefficient|round3}} |
{% endfor %}

---

## 4. Authorship and review Gini (all PRs)

| Period | Authorship Gini | Top-10 authors | Review Gini | Top-10 reviewers |
|--------|----------------:|---------------:|------------:|-----------------:|
{% for item in gini_periods %}
| {{item.period}} | {{item.author_gini|round3}} | {{item.author_top10|pct}} | {{item.review_gini|round3}} | {{item.review_top10|pct}} |
{% endfor %}

---

## 5. Conflict resolution over time

| Year | PRs | Conflicts | Conflict rate | Avg resolution (days) |
|------|----:|----------:|--------------:|----------------------:|
{% for item in conflict_years %}
| {{item.year}} | {{item.total_prs_in_year|int}} | {{item.total_conflicts|int}} | {{item.conflict_rate|pct}} | {{item.avg_resolution_time_days|round1}} |
{% endfor %}

**All-years**: {{conflict_total|int}} conflicts across {{conflict_prs|int}} PRs ({{conflict_rate|pct}}).

---

## Reading

Process improved (zero-review self-merge nearly gone; reviews got longer). Power did not diffuse: top-3 merge share stays high, and authorship/review Gini stay extreme. Conflicts are common and often resolve by merge anyway — disagreement is not a veto.

Informal-channel volume is **not** in these GitHub clocks. See `CROSS_PLATFORM_NETWORKS.md` for era-stratified informal→GitHub flow.

**Generated by**: `scripts/reporting/generate_from_templates.py`
