# Vocabulary audit

**Date:** {{generated_date}}  
**Status:** Schema seed (phrase strings only; counts empty)  
**Machine-readable:** `findings/data/governance_episode_ledger.json`

{{pin}}

Phrase **frequency** by term lives in `LANGUAGE_EVOLUTION.md`. This table is phrase × process/technical/ambiguous context. `count` stays empty until a labeled counter exists. Do not auto-count IRC/mail hits without that labeler.

---

| Phrase | context_type | episode_ids | count | corpus_cites |
|--------|--------------|-------------|------:|--------------|
{% for item in phrases %}
| {{item.phrase}} | {{item.context_type}} | {{item.episode_ids}} | {{item.count}} | {{item.corpus_cites}} |
{% endfor %}

**Generated by:** `scripts/reporting/generate_from_templates.py`
